# Task B: SVM

## 0. Load the preprocessed data
**We will use the preprocessed dataset after image processing and PCA. It characterizes 4 different classes (tumor or not) based on 200 features.** 

In [1]:
# Import necessary libraries
import pickle
import numpy as np
import pandas as pd

In [2]:
# Load preprocessed data with help of pickle.
with open('DataAfterProcess/images_AfterProcess_TaskA.pickle', 'rb') as handle:
    X = pickle.load(handle)
    
with open('DataAfterProcess/label_AfterProcess.pickle', 'rb') as handle:
    y = pickle.load(handle)
    
# Check result.
print(X.shape, y.shape) 

(3000, 200) (3000,)


### Train Test Split

**Split data into a training set (90%) and a test set (10%). Note that the test set here comes from the dataset.zip file, not the test.zip file.**

In [3]:
# Import necessary libraries
from sklearn.model_selection import train_test_split

In [4]:
# Split data into a training set and a test set (90% training and 10% testing data).
# Notice that all random state is chosen as fixed in this assignment to ensure reproducibility.
X_train, X_test, y_train, y_test = train_test_split(X,y, 
                                                    test_size=0.1, random_state=3)

# Split training set into a new training set and a validation set (90% training and 10% validation data).
X_train_new, X_val, y_train_new, y_val = train_test_split(X_train,y_train, 
                                                          test_size=0.1, random_state=3)

# Check result.
print(X_train_new.shape, y_train_new.shape, X_val.shape, y_val.shape, X_test.shape, y_test.shape) 
print('train set: {} | val set: {} | test set: {}'.format(round(len(y_train_new)/len(X),3), 
                                                          round(len(y_val)/len(X),3),
                                                          round(len(y_test)/len(X),3)))

(2430, 200) (2430,) (270, 200) (270,) (300, 200) (300,)
train set: 0.81 | val set: 0.09 | test set: 0.1


## 1. Train a SVM model
**Firstly, we train a SVM model without hyperparameter tuning in order to compare with model trained from GridsearchCV in next step.**

In [5]:
# Import necessary libraries
from sklearn.svm import SVC

In [6]:
# Call the SVC() model from sklearn and fit the model to the training data.
# Notice that all random state is chosen as fixed in this assignment to ensure reproducibility.
svm = SVC(random_state=0, decision_function_shape='ovo')
svm.fit(X_train_new, y_train_new)

SVC(decision_function_shape='ovo', random_state=0)

### Model validation
**Evaluate the model per validation set by checking confusion matrix, classification report, accuracy score and cohen kappa score.**

In [7]:
# Import necessary libraries
from sklearn.metrics import confusion_matrix, classification_report, accuracy_score, cohen_kappa_score

In [8]:
# Get predictions from the model.
y_pred = svm.predict(X_val)

# Print model performance: Confusion matrix, accuracy score, classification report and cohen kappa score.
print('Confusion matrix: \n', confusion_matrix(y_val, y_pred), '\n')
print('Accuracy on validation set: ', accuracy_score(y_val, y_pred), '\n')
print('Classification report: \n', classification_report(y_val, y_pred), '\n') 
print('cohen_kappa score：',cohen_kappa_score(y_val, y_pred))

Confusion matrix: 
 [[32  1  4  2]
 [ 5 63  6  0]
 [ 3 10 59  1]
 [ 0  0  2 82]] 

Accuracy on validation set:  0.8740740740740741 

Classification report: 
               precision    recall  f1-score   support

           0       0.80      0.82      0.81        39
           1       0.85      0.85      0.85        74
           2       0.83      0.81      0.82        73
           3       0.96      0.98      0.97        84

    accuracy                           0.87       270
   macro avg       0.86      0.86      0.86       270
weighted avg       0.87      0.87      0.87       270
 

cohen_kappa score： 0.8285426122037317
