# Task B: SVM

## 0. Load the preprocessed data
**We will use the preprocessed dataset after image processing and PCA. It characterizes 4 different classes (tumor or not) based on 200 features.** 

In [7]:
# Import necessary libraries
import pickle
import numpy as np
import pandas as pd

In [8]:
# Load preprocessed data with help of pickle.
with open('DataAfterProcess/images_AfterProcess_TaskA.pickle', 'rb') as handle:
    X = pickle.load(handle)
    
with open('DataAfterProcess/label_AfterProcess.pickle', 'rb') as handle:
    y = pickle.load(handle)
    
# Check result.
print(X.shape, y.shape) 

(3000, 200) (3000,)


In [9]:
# Load preprocessed data with help of pickle.
with open('DataAfterProcess/test_images_AfterProcess_TaskA.pickle', 'rb') as handle:
    X_test = pickle.load(handle)
    
with open('DataAfterProcess/test_label_AfterProcess.pickle', 'rb') as handle:
    y_test = pickle.load(handle)
    
# Check result.
print(X_test.shape, y_test.shape) 

(200, 200) (200,)


### Train Test Split

**Split data into a training set (90%) and a test set (10%). Note that the test set here comes from the dataset.zip file, not the test.zip file.**

In [10]:
# Import necessary libraries
from sklearn.model_selection import train_test_split

In [11]:
# Split data into a training set and a test set (90% training and 10% testing data).
# Notice that all random state is chosen as fixed in this assignment to ensure reproducibility.
X_train, X_val, y_train, y_val = train_test_split(X,y, 
                                                  test_size=0.1, random_state=1)

# Check result.
print(X_train.shape, y_train.shape, X_val.shape, y_val.shape, X_test.shape, y_test.shape) 
print('train set: {} | val set: {} | test set: {}'.format(round(len(y_train)/len(X),3), 
                                                          round(len(y_val)/len(X),3),
                                                          round(len(y_test)/len(X),3)))

(2700, 200) (2700,) (300, 200) (300,) (200, 200) (200,)
train set: 0.9 | val set: 0.1 | test set: 0.067


## 1. Train a SVM model
**Firstly, we train a SVM model without hyperparameter tuning in order to compare with model trained from GridsearchCV in next step.**

In [12]:
# Import necessary libraries
from sklearn.svm import SVC

In [13]:
# Call the SVC() model from sklearn and fit the model to the training data.
# Notice that all random state is chosen as fixed in this assignment to ensure reproducibility.
svm = SVC(random_state=0, decision_function_shape='ovo')
svm.fit(X_train, y_train)

SVC(decision_function_shape='ovo', random_state=0)

### Model validation
**Evaluate the model per validation set by checking confusion matrix, classification report, accuracy score and cohen kappa score.**

In [14]:
# Import necessary libraries
from sklearn.metrics import confusion_matrix, classification_report, accuracy_score, cohen_kappa_score

In [16]:
# Get predictions from the model.
y_pred = svm.predict(X_val)

# Print model performance: Confusion matrix, accuracy score, classification report and cohen kappa score.
print('Confusion matrix: \n', confusion_matrix(y_val, y_pred), '\n')
print('Accuracy on validation set: ', accuracy_score(y_val, y_pred), '\n')
print('Classification report: \n', classification_report(y_val, y_pred), '\n') 
print('cohen_kappa score：',cohen_kappa_score(y_val, y_pred))

Confusion matrix: 
 [[36  1  2  0]
 [ 1 71 17  2]
 [ 0 13 70  2]
 [ 0  3  2 80]] 

Accuracy on validation set:  0.8566666666666667 

Classification report: 
               precision    recall  f1-score   support

           0       0.97      0.92      0.95        39
           1       0.81      0.78      0.79        91
           2       0.77      0.82      0.80        85
           3       0.95      0.94      0.95        85

    accuracy                           0.86       300
   macro avg       0.88      0.87      0.87       300
weighted avg       0.86      0.86      0.86       300
 

cohen_kappa score： 0.803575235252916
